version: "3"

networks:
  default:

services:
  nestjs:
    build: .
    container_name: nestjs
    restart: always
    stdin_open: true
    tty: true
    env_file: .env
    depends_on:
      - mysql
    ports:
      - "${NESTJS_LOCAL_PORT}:${NESTJS_DOCKER_PORT}"
    volumes:
      - ./:/app
    networks:
      - default

  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    stdin_open: true
    tty: true
    env_file: .env
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    ports:
      - "${MYSQL_LOCAL_PORT}:${MYSQL_DOCKER_PORT}"
    volumes:
      - mysql-volume:/var/lib/mysql
    networks:
      - default

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    stdin_open: true
    tty: true
    depends_on:
      - mysql
    env_file: .env
    environment:
      PMA_HOST: mysql
      PMA_PORT: "${MYSQL_DOCKER_PORT}"
    ports:
      - "8080:80"
    networks:
      - default
volumes:
  mysql-volume: